#!/usr/bin/env bash
echo -x

FILE="zellij-x86_64-unknown-linux-musl.tar.gz"
URL="https://github.com/zellij-org/zellij/releases/download/v0.30.0/$FILE"

cd /tmp
rm -r zellij

wget -O "$FILE" "$URL" && tar -xvf "$FILE"
if [[ -f zellij ]]; then
	chmod +x zellij
	mkdir -p ~/.local/bin
	cp ./zellij ~/.local/bin/zellij
	rm -r zellij*
fi
