#!/usr/bin/env sh
set -ex
[ $(which fzf) ] && exit 1

if [ ! -d ~/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --bin
fi

BIN=~/.local/bin
mkdir -p $BIN
ln -sf ~/.fzf/bin/fzf $BIN/fzf
ln -sf ~/.fzf/bin/fzf-tmux $BIN/fzf-tmux

exit 0
