#!/usr/bin/env bash
set -ex

# fetch static binary
cd /tmp
wget -qc 'https://github.com/jarun/nnn/releases/download/v3.5/nnn-static-3.5.x86_64.tar.gz' -O 'nnn.tar.gz'
tar -zxvf 'nnn.tar.gz' 'nnn-static'
chmod u+x 'nnn-static'

# copy binary to local-bin
BIN="$HOME/.local/bin"
mkdir -p "$BIN" && mv /tmp/nnn-static "$BIN/nnn"

# fetch plugins
curl -Ls 'https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs' | bash
